{
 "title": "Electricity / Gas / Water",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "electricity_tariff_1", "label": "Electricity Low Tariff", "query": "0.236289" },
   { "name": "electricity_tariff_2", "label": "Electricity High Tariff", "query": "0.244759" },
   { "name": "gas_tariff", "label": "Gas Tariff", "query": "0.864739" },
   { "name": "water_tariff", "label": "Water Tariff", "query": "1.33" }
  ]
 },
 "panels": [
  {
   "title": "Electricity usage / h",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_hourly_usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "dsmr/reading/electricity_hourly_usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Gas usage / h",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gas",
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/gas_hourly_usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "dsmr/reading/gas_hourly_usage" }
     ]
    }
   ]
  },
  {
   "title": "Water usage / h",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "water",
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"watermeter/reading/current_value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n    |> timedMovingAverage(every: 5m, period: 1h)\n    |> difference()\n    |> timedMovingAverage(every: 30m, period: 1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "watermeter/reading/current_value"
      }
     ]
    }
   ]
  },
  {
   "title": "Electricity consumption / h",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_hourly_usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "dsmr/reading/electricity_hourly_usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Gas consumption / h",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas",
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/gas_hourly_usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "dsmr/reading/gas_hourly_usage" }
     ]
    }
   ]
  },
  {
   "title": "Water consumption / h",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"watermeter/reading/current_value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n    |> timedMovingAverage(every: 5m, period: 1h)\n    |> difference()\n    |> timedMovingAverage(every: 30m, period: 1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "watermeter/reading/current_value"
      }
     ]
    }
   ]
  },
  {
   "title": "Electricity cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_1\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> increase()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            _value: r._value *  ${electricity_tariff_1},\n        }),\n    )"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_2\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> increase()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            _value: r._value *  ${electricity_tariff_2},\n        }),\n    )"
    }
   ]
  },
  {
   "title": "Gas cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/consumption/gas/delivered\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> increase()\n    |> map(\n        fn: (r) => ({r with\n            _value: r._value * ${gas_tariff}\n        }),\n    )"
    }
   ]
  },
  {
   "title": "Water cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"watermeter/reading/current_value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> increase()\n    |> map(\n        fn: (r) => ({r with\n            _value: (r._value / 1000.0) * ${water_tariff}\n        }),\n    )"
    }
   ]
  },
  {
   "title": "Total cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_1\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n    |> increase()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            electricity_1: r._value * ${electricity_tariff_1},\n        }),\n    )"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_2\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n    |> increase()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            electricity_2: r._value * ${electricity_tariff_2},\n        }),\n    )"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/consumption/gas/delivered\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n    |> increase()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            gas: r._value * 0.864739,\n        }),\n    )"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"watermeter/reading/current_value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n    |> increase()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            water: r._value / 1000.0 * 1.33,\n        }),\n    )"
    }
   ]
  },
  {
   "title": "Electricity cumulative",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_1\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> increase()"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_2\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> increase()"
    }
   ]
  },
  {
   "title": "Gas cumulative",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"dsmr/consumption/gas/delivered\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> increase()"
    }
   ]
  },
  {
   "title": "Water cumulative",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"watermeter/reading/current_value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> increase()\n"
    }
   ]
  },
  {
   "title": "Electricity usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_currently_delivered\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "dsmr/reading/electricity_currently_delivered"
      }
     ]
    }
   ]
  },
  {
   "title": "Gas usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gas",
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"dsmr/consumption/gas/delivered\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> derivative()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "dsmr/consumption/gas/delivered" }
     ]
    }
   ]
  },
  {
   "title": "Water usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "water",
     "query": "from(bucket: \"smart_meter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"watermeter/reading/current_value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> derivative()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "watermeter/reading/current_value"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_1\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> derivative()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            electricity_1: r._value *  ${electricity_tariff_1},\n        }),\n    )"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/reading/electricity_delivered_2\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> derivative()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            electricity_2: r._value *  ${electricity_tariff_2},\n        }),\n    )"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"watermeter/reading/current_value\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> derivative()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            water: (r._value / 1000.0) * ${water_tariff}\n        }),\n    )"
    },
    {
     "query": "from(bucket: \"smart_meter\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"topic\"] == \"dsmr/consumption/gas/delivered\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> derivative()\n    |> map(\n        fn: (r) => ({\n            _time: r._time,\n            gas: r._value * ${gas_tariff}\n        }),\n    )"
    }
   ]
  }
 ]
}